### ISSUE TITLE
Release tag does not include complete library.

### ISSUE THREAD

**Issue by tomgud** [webmozart/json#16]
I think most of your library is missing from the release. See release tag 1.2.2 here : https://github.com/webmozart/json/tree/a1fb3da904b8364e3db47eed68f76bfb6cd0031a/src

`composer require webmozart/json` gives `"webmozart/json": "^1.2"`, installs version 1.2.2

Comparing repository at tag 1.2.2 with master reveals obvious lack of code : https://github.com/webmozart/json/tree/master/src

**Comment by webmozart** [comment]
Hi Tomas, thank you for reporting this issue! :) The missing code you are talking about was added after 1.2 and will be released with 1.3. This version will be released in the coming weeks

Hope this helps! :)

**Comment by tomgud** [comment]
Great to hear :+1: 

I just downloaded the master branch and worked from there.
