### ISSUE TITLE
composer installs outdated package

### ISSUE THREAD

**Issue by skvskv** [webmozart/json#17]
Hello!

For some reason, ````composer require webmozart/json```` yields outdated package from Jan 14, which does not contain none of VersionFieldVersioner, SchemaUriVersioner, MigrationManager, MigratingConverter, JsonMigration, JsonConverter, ValidatingConverter, etc.

Please advise asap.

**Comment by xabbuh** [comment]
By default, Composer will only install stable package releases (the last release of `webmozart/json` is version 1.2.2 from January 14). If you want to use new features from the upcoming `1.3` release, you have to require an unstable version like this:

```bash
$ composer require webmozart/json:~1.3@dev
```

**Comment by skvskv** [comment]
Thanks! I was so excited about new features and didn't notice they're from upcoming release. Sorry for bothering!

**Comment by xyNNN** [comment]
This issue should be closed or @skvskv @webmozart ? ;)
