### ISSUE TITLE
Working with empty keys in JSON

### ISSUE THREAD

**Issue by borNfreee** [webmozart/json#19]
Hi,

I have empty keys in my json that represent empty values in dropdowns. When I use native `json_decode`, empty keys are transformed to `_empty_` string. This is a known PHP bug: https://bugs.php.net/bug.php?id=46600

So the following json decoded and encoded again is not the same as original:

```php
$json = '{"test": {"": "foo"}}';
var_dump(json_encode(json_decode($json))); // "{"test":{"_empty_":"foo"}}"
```

Notice an `_empty_` key instead of `''` key.

The same behaviour is when I use this package:

```php
$encoder = new JsonEncoder();
$decoder = new JsonDecoder();

$decoded = $decoder->decode('{"test": {"": "foo"}}');
dump($decoded);
dump($encoder->encode($decoded));

// output
{#1316
  +"test": {#1317
    +"_empty_": "foo"
  }
}
"{"test":{"_empty_":"foo"}}"
```

Do you have any recommendations on how to avoid this? I cant use `assoc = true` because in my json there are many keys with empty objects that are converted back as arrays when you use `assoc = true`

For now I use an ugly solution with replacing all `_empty_` keys with empty strings:

```php
private function jsonEncode($content)
{
    $jsonString = json_encode($content, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

    $fixedJsonString = str_replace('"_empty_":', '"":', $jsonString);

    return $fixedJsonString;
}
```

**Comment by webmozart** [comment]
Hi @borNfreee! I think we can add this fix to the library. Do you want to create a PR?

**Comment by borNfreee** [comment]
Yes, I can try to create a PR.

Good news that this bug is fixed in PHP 7.1 -> https://3v4l.org/SAHin
So wee need this fix for earlier versions of PHP

**Comment by webmozart** [comment]
I just tried to fix this. However, it doesn't seem possible to fix this properly for earlier versions than 7.1, since empty attributes aren't properly supported before that: https://3v4l.org/jouOS

**Comment by borNfreee** [comment]
Sorry, didn't understand why it's not possible.
What I'm trying to solve is this problem https://3v4l.org/SnXoR:

```php
$originalJson = '{"":"test"}';
$decoded = json_decode($originalJson);
$json = json_encode($decoded);

// $json = {"":"test"} for PHP >=7.1
// $json = {"_empty_":"test"} for PHP <7.1

var_dump($json);
var_dump($originalJson);

var_dump($json === $originalJson); // TRUE for PHP 7.1, FALSE for PHP <7.1
```

Applying fix from the first comment, we can manually remove `_empty_` from result json. In this case decoded and encoded JSON string will be the same.

**Comment by webmozart** [comment]
I see. This is fixed now :)
