### ISSUE TITLE
SCIM

### ISSUE THREAD

**Issue by Spomky** [webmozart/json#28]
This is not a bug report bug a general question about this library, validation and SCIM (https://tools.ietf.org/html/rfc7643).

Do you know if it is possible to use schemas described in the RFC7643 to validate SCIM resources using that library?

**Comment by webmozart** [comment]
@Spomky As I'm not familiar with SCIM and its schemas, I can't answer that question. Does SCIM use the regular JSON standard? Does it use JSON schemas or some other schema notation?
