### ISSUE TITLE
Is the RefResolver intentionally not being used?

### ISSUE THREAD

**Issue by graste** [webmozart/json#8]
Thanks for this library. I'm using it and now that I'm trying to use references in schemas I'm asking myself whether you not resolve references on purpose? See [this gist](https://gist.github.com/graste/2fccfa710a375f93105d) for an example. Without doing the reference resolution the schema contains

```
    "properties": {
        "billing_address": {
            "$ref": "#/definitions/address"
        },
        "shipping_address": {
            "$ref": "#/definitions/address"
        }
    },
```

instead of

```
"properties": {
        "billing_address": {
            "type": "object",
            "properties": {
                "street_address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            },
            "required": [
                "street_address",
                "city",
                "state"
            ],
            "id": "file:///srv/www/json-schema/schema-address.json#/definitions/address"
        },
        "shipping_address": {
            "type": "object",
            "properties": {
                "street_address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            },
            "required": [
                "street_address",
                "city",
                "state"
            ],
            "id": "file:///srv/www/json-schema/schema-address.json#/definitions/address"
        }
    }
```

Apart from the underlying library [not supporting all cases](https://github.com/justinrainbow/json-schema/pull/182) of `definitions` and `$ref` usage I just wanted to make sure whether you're deviating intentionally from the README example of [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema).

**Comment by webmozart** [comment]
Thank you for reporting this issue @graste! No, this was not intentional. In fact I think that the README changed since I wrote the integration for the schema validator.

Could you maybe open a PR that changes the `JsonValidator` accordingly?

**Comment by graste** [comment]
I'm not sure whether I've got time for this in the near future, so no promises – but we'll see. :-)

**Comment by graste** [comment]
I'm not sure whether this library needs to be changed a bit as the schema file loading can be handled by justin/json-schema UriRetriever. Are you sure the references in the meta schema ever worked (as in had been resolved)?

**Comment by webmozart** [comment]
@graste At the time I integrated the schema validator, it did not support references (AFAIR), so: no. :)

**Comment by graste** [comment]
I see. :-) I guess thoroughly thinking about this or waiting for the library to improve on the ref resolving may be a good option. This issue may be the reminder on that?

**Comment by webmozart** [comment]
Sure :)

**Comment by webmozart** [comment]
This is supported in the latest version :)

**Comment by graste** [comment]
Will give it a try when I have a need in upcoming stuff. Thank you for your work. The migration stuff is nice as well. :-)
